receivers:
  azureeventhub/logs:
    connection: ${env:EVENTHUB_CONNECTION_STRING_LOGS}
    group: ${env:EVENTHUB_CONSUMER_GROUP}
    format: "azure"
    storage: file_storage/local

processors:
  transform/flatten_azure_logs:
    error_mode: "propagate"
    log_statements:
      - context: log
        statements:
          - set(attributes["processed_by_this"], true) where attributes["azure.properties"] != nil and IsMap(attributes["azure.properties"])
          - flatten(attributes["azure.properties"]) where attributes["azure.properties"] != nil and IsMap(attributes["azure.properties"])
          - merge_maps(attributes, ParseJSON(attributes["azure.properties"]), "upsert") where attributes["azure.properties"] != nil and IsMap(attributes["azure.properties"])
          #- delete_key(attributes, "azure.properties") where attributes["azure.properties"] != nil and IsMap(attributes["azure.properties"])
          # - flatten(attributes["azure.properties.log"], "azure.properties") where attributes["azure.properties.log"] != nil and IsMap(attributes["azure.properties.log"])
          # - delete_key(attributes, "azure.properties.log") where attributes["azure.properties.log"] != nil and IsMap(attributes["azure.properties.log"])


  filter/only_azure_logs:
    logs:
      log_record:
        - IsMap(attributes["azure.properties.log"])

exporters:
  otlp/honeycomb-logs:
    endpoint: "api.eu1.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "azure-logs3"
  debug:
    verbosity: detailed

extensions: 
  health_check:
    endpoint: 0.0.0.0:13133
  file_storage/local:
    directory: /var/lib/otelcol/storage

service:
  telemetry:
    logs:
      level: DEBUG
  extensions: [health_check, file_storage/local]
  pipelines:
    # logs/azure:
    #   receivers: [azureeventhub/logs]
    #   processors: [transform/flatten_azure_logs]
    #   exporters: [otlp/honeycomb-logs]

    logs/console:
      receivers: [azureeventhub/logs]
      processors: [filter/only_azure_logs, transform/flatten_azure_logs]
      exporters: 
        - debug
      # - otlp/honeycomb-logs
