receivers:
  azureeventhub/logs:
    connection: ${env:EVENTHUB_CONNECTION_STRING_LOGS}
    group: ${env:EVENTHUB_CONSUMER_GROUP}
    format: "azure"
  azureeventhub/metrics:
    connection: ${env:EVENTHUB_CONNECTION_STRING_METRICS}
    group: ${env:EVENTHUB_CONSUMER_GROUP}
    format: "azure"
 
processors:
  batch:
  transform/flatten_azure_logs:
    log_statements:
      - context: log
        conditions:
          - attributes["azure.properties"] != nil and IsMap(attributes["azure.properties"])
        statements:
          - flatten(attributes["azure.properties"], "azure.properties", 2)
          - merge_maps(attributes, attributes["azure.properties"], "upsert") 
          - delete_key(attributes, "azure.properties")      
      - context: log
        conditions:
          - attributes["azure.properties.log"] != nil and Substring(attributes["azure.properties.log"], 0, 2) == "{\""
        statements:
          - set(attributes["azure.properties.log_map"], ParseJSON(attributes["azure.properties.log"])) 
          - flatten(attributes["azure.properties.log_map"], "azure.properties.log") 
          - merge_maps(attributes, attributes["azure.properties.log_map"], "upsert")
          - delete_key(attributes, "azure.properties.log")
          - delete_key(attributes, "azure.properties.log_map")

  transform/normalize_azure_logs:
    log_statements:
      - context: log
        statements:
          - set(resource.attributes["k8s.pod.name"], attributes["azure.properties.pod"])
          - delete_key(attributes, "azure.properties.pod")
          - set(resource.attributes["container.id"], attributes["azure.properties.containerID"])
          - delete_key(attributes, "azure.properties.containerID")


exporters:
  otlp/honeycomb-metrics:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "azure-metrics"
  otlp/honeycomb-logs:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "azure-logs"
  debug:
    verbosity: detailed

extensions: 
  health_check:
    endpoint: 0.0.0.0:13133
  file_storage/local:
    directory: /var/lib/otelcol/state

service:
  extensions: [health_check]
  pipelines:
    metrics/azure:
      receivers: [azureeventhub/metrics]
      processors: [batch]
      exporters: [otlp/honeycomb-metrics]
    logs/azure:
      receivers: [azureeventhub/logs]
      processors:
        - transform/flatten_azure_logs
        - transform/normalize_azure_logs
        - batch
      exporters: [otlp/honeycomb-logs]
