receivers:
  azureeventhub/logs:
    connection: ${env:EVENTHUB_CONNECTION_STRING_LOGS}
    group: ${env:EVENTHUB_CONSUMER_GROUP}
    format: "azure"
  azureeventhub/metrics:
    connection: ${env:EVENTHUB_CONNECTION_STRING_METRICS}
    group: ${env:EVENTHUB_CONSUMER_GROUP}
    format: "azure"
 
processors:
  batch:
  transform/flatten_azure_logs:
    log_statements:
      - context: log
        statements:
          - flatten(attributes["azure.properties.log"], "azure.properties.expanded") where attributes["azure.properties.log"] != nil

exporters:
  otlp/honeycomb-metrics:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "azure-metrics"
  otlp/honeycomb-logs:
    endpoint: "api.honeycomb.io:443"
    headers:
      "x-honeycomb-team": "${env:HONEYCOMB_API_KEY}"
      "x-honeycomb-dataset": "azure-logs"
  debug:
    verbosity: detailed

extensions: 
  health_check:
    endpoint: 0.0.0.0:13133

service:
  telemetry:
    logs:
      level: DEBUG
  extensions: [health_check]
  pipelines:
    metrics/azure:
      receivers: [azureeventhub/metrics]
      processors: [batch]
      exporters: [otlp/honeycomb-metrics]
    logs/azure:
      receivers: [azureeventhub/logs]
      processors: [transform/flatten_azure_logs, batch]
      exporters: [otlp/honeycomb-logs]